// Code generated by avero generate. DO NOT EDIT.
//
// The source of this file is the client interface of this package. Change the
// interface and its directives. Run `avero generate`. Do not edit this
// file by hand.

package example

import (
	"context"

	"github.com/alternayte/avero/codegen/client"
)

// exampleClient calls the Example service over HTTP.
type exampleClient struct {
	rt *client.Client
}

// The assignment proves that the generated type satisfies the interface.
var _ Example = (*exampleClient)(nil)

// NewExample returns a client of the Example service.
//
// The directive states the base address https://api.example.com. An option after it replaces a
// default, so a test points the client at httptest.
func NewExample(opts ...client.Option) (Example, error) {
	settings := []client.Option{
		client.WithBaseURL("https://api.example.com"),
		client.WithAuth(client.Auth("bearer")),
		client.WithTimeout(client.MustDuration("5s")),
		client.WithAttempts(3),
		client.WithBackoff(client.MustDuration("10ms")),
	}
	rt, err := client.New("Example", append(settings, opts...)...)
	if err != nil {
		return nil, err
	}
	return &exampleClient{rt: rt}, nil
}

// GetThing calls GET /things/{id}.
func (c *exampleClient) GetThing(ctx context.Context, id string) (Thing, error) {
	var out Thing
	req := client.Request{
		Op:         "GetThing",
		Method:     "GET",
		Path:       "/things/" + client.Escape(id),
		Idempotent: true,
	}
	if err := c.rt.Do(ctx, req, &out); err != nil {
		return out, err
	}
	return out, nil
}

// ListThings calls GET /things.
func (c *exampleClient) ListThings(ctx context.Context, opts ListOptions) (List, error) {
	var out List
	req := client.Request{
		Op:         "ListThings",
		Method:     "GET",
		Path:       "/things",
		Idempotent: true,
	}
	req.Query = client.NewQuery()
	req.Query.Set("page", client.Int(int64(opts.Page)))
	if opts.Search != "" {
		req.Query.Set("q", opts.Search)
	}
	req.Query.Set("full", client.Bool(opts.Full))
	if opts.Limit != nil {
		req.Query.Set("limit", client.Int(int64(*opts.Limit)))
	}
	req.Header = client.NewHeader()
	req.Header.Set("X-Api-Key", opts.Key)
	if opts.Trace != "" {
		req.Header.Set("X-Trace", opts.Trace)
	}
	if err := c.rt.Do(ctx, req, &out); err != nil {
		return out, err
	}
	return out, nil
}

// CreateThing calls POST /things.
func (c *exampleClient) CreateThing(ctx context.Context, body NewThing) (*Thing, error) {
	out := new(Thing)
	req := client.Request{
		Op:         "CreateThing",
		Method:     "POST",
		Path:       "/things",
		Idempotent: false,
		Body:       body,
	}
	if err := c.rt.Do(ctx, req, out); err != nil {
		return nil, err
	}
	return out, nil
}

// DeleteThing calls DELETE /things/{id}.
func (c *exampleClient) DeleteThing(ctx context.Context, id string) error {
	req := client.Request{
		Op:         "DeleteThing",
		Method:     "DELETE",
		Path:       "/things/" + client.Escape(id),
		Idempotent: true,
	}
	return c.rt.Do(ctx, req, nil)
}

// GetAccountThing calls GET /accounts/{account}/things/{id}.
func (c *exampleClient) GetAccountThing(ctx context.Context, account int, id string) (Thing, error) {
	var out Thing
	req := client.Request{
		Op:         "GetAccountThing",
		Method:     "GET",
		Path:       "/accounts/" + client.Int(int64(account)) + "/things/" + client.Escape(id),
		Idempotent: true,
	}
	if err := c.rt.Do(ctx, req, &out); err != nil {
		return out, err
	}
	return out, nil
}
