// Code generated by avero generate. DO NOT EDIT.
//
// The source of this file is the client interface of this package. Change the
// interface and its directives. Run `avero generate`. Do not edit this
// file by hand.

package payments

import (
	"context"

	"github.com/alternayte/avero/codegen/client"
)

// paymentsClient calls the Payments service over HTTP.
type paymentsClient struct {
	rt *client.Client
}

// The assignment proves that the generated type satisfies the interface.
var _ Payments = (*paymentsClient)(nil)

// NewPayments returns a client of the Payments service.
//
// The directive states the base address https://api.payments.example.com. An option after it replaces a
// default, so a test points the client at httptest.
func NewPayments(opts ...client.Option) (Payments, error) {
	settings := []client.Option{
		client.WithBaseURL("https://api.payments.example.com"),
		client.WithAuth(client.Auth("bearer")),
		client.WithTimeout(client.MustDuration("5s")),
		client.WithAttempts(3),
	}
	rt, err := client.New("Payments", append(settings, opts...)...)
	if err != nil {
		return nil, err
	}
	return &paymentsClient{rt: rt}, nil
}

// GetCharge calls GET /charges/{id}.
func (c *paymentsClient) GetCharge(ctx context.Context, id string) (Charge, error) {
	var out Charge
	req := client.Request{
		Op:         "GetCharge",
		Method:     "GET",
		Path:       "/charges/" + client.Escape(id),
		Idempotent: true,
	}
	if err := c.rt.Do(ctx, req, &out); err != nil {
		return out, err
	}
	return out, nil
}

// CreateCharge calls POST /charges.
func (c *paymentsClient) CreateCharge(ctx context.Context, body NewCharge) (*Charge, error) {
	out := new(Charge)
	req := client.Request{
		Op:         "CreateCharge",
		Method:     "POST",
		Path:       "/charges",
		Idempotent: false,
		Body:       body,
	}
	if err := c.rt.Do(ctx, req, out); err != nil {
		return nil, err
	}
	return out, nil
}
