// Code generated by drel. DO NOT EDIT.

package model

import (
	"context"

	"github.com/alternayte/drel"
	uuid "github.com/google/uuid"
)

var Tasks = struct {
	ID        drel.ComparableColumn[uuid.UUID]
	Title     drel.StringColumn
	Done      drel.BoolColumn
	CreatedAt drel.TimeColumn
	UpdatedAt drel.TimeColumn
}{
	ID:        drel.NewComparableCol[uuid.UUID]("id"),
	Title:     drel.NewStringCol("title"),
	Done:      drel.NewBoolCol("done"),
	CreatedAt: drel.NewTimeCol("created_at"),
	UpdatedAt: drel.NewTimeCol("updated_at"),
}

func scanTask(row drel.Row) (*Task, error) {
	p := &Task{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	err := row.Scan(idPtr, &p.Title, &p.Done, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	return p, nil
}

type taskSnapshot struct {
	Title string
	Done  bool
}

func snapshotTask(p *Task) any {
	return taskSnapshot{Title: p.Title, Done: p.Done}
}

func diffTask(p *Task, snap any) []drel.FieldChange {
	s := snap.(taskSnapshot)
	var changes []drel.FieldChange
	if p.Title != s.Title {
		changes = append(changes, drel.FieldChange{Column: "title", Value: p.Title})
	}
	if p.Done != s.Done {
		changes = append(changes, drel.FieldChange{Column: "done", Value: p.Done})
	}
	return changes
}

func taskPKValue(p *Task) any {
	return p.ID()
}

func taskColumnValue(p *Task, idx int) any {
	switch idx {
	case 0:
		return p.ID()
	case 1:
		return p.Title
	case 2:
		return p.Done
	case 3:
		return p.CreatedAt()
	case 4:
		return p.UpdatedAt()
	}
	return nil
}

func taskInsertColumns(p *Task) ([]string, []any) {
	return []string{"title", "done"}, []any{p.Title, p.Done}
}

func taskScanReturning(p *Task, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

func taskNormalizeKey(v any) any {
	return drel.NormalizeUUIDKey(v)
}

func taskKeyIsZero(p *Task) bool {
	var zero uuid.UUID
	return p.ID() == zero
}

func taskScanGenerated(p *Task, row drel.Row) error {
	_, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(createdAtPtr, updatedAtPtr)
}

var TaskMeta = drel.ModelMeta[Task]{
	Table:         "tasks",
	Columns:       []string{"id", "title", "done", "created_at", "updated_at"},
	PKColumn:      "id",
	Scan:          scanTask,
	Snapshot:      snapshotTask,
	Diff:          diffTask,
	PKValue:       taskPKValue,
	InsertColumns: taskInsertColumns,
	ScanReturning: taskScanReturning,
	ColumnValue:   taskColumnValue,
	NormalizeKey:  taskNormalizeKey,
	KeyStrategy:   drel.KeyAppAssigned,
	GenerateKey:   drel.UUIDv7Key,
	SetKey:        func(p *Task, key any) { p.SetID(key.(uuid.UUID)) },
	KeyIsZero:     taskKeyIsZero,
	ScanGenerated: taskScanGenerated,
}

type TaskRepository struct {
	*drel.Repository[Task]
}

func (r *TaskRepository) FindByID(ctx context.Context, id uuid.UUID) (*Task, error) {
	return r.Find(ctx, id)
}

type TxTaskRepository struct {
	*drel.TxRepository[Task]
}

func (r *TxTaskRepository) FindByID(ctx context.Context, id uuid.UUID) (*Task, error) {
	return r.Find(ctx, id)
}
