package client

import (
	"fmt"
	"go/format"
	"strconv"
	"strings"
)

// generatedHeader is the line that every Go tool recognises. See go/build.
const generatedHeader = "// Code generated by avero generate. DO NOT EDIT."

// runtimeImport is the package that the generated code calls.
const runtimeImport = "github.com/alternayte/avero/codegen/client"

// emit writes the source of one generated client file.
func emit(pkg string, ifaces []iface) ([]byte, error) {
	var body strings.Builder
	for _, in := range ifaces {
		emitClient(&body, in)
		for _, m := range in.Methods {
			emitMethod(&body, in, m)
		}
	}

	var head strings.Builder
	head.WriteString(generatedHeader + "\n//\n")
	head.WriteString("// The source of this file is the client interface of this package. Change the\n")
	head.WriteString("// interface and its directives. Run `avero generate`. Do not edit this\n")
	head.WriteString("// file by hand.\n\n")
	fmt.Fprintf(&head, "package %s\n\n", pkg)
	head.WriteString("import (\n\t\"context\"\n\n\t" + strconv.Quote(runtimeImport) + "\n)\n\n")

	return format.Source([]byte(head.String() + body.String()))
}

// receiver returns the name of the generated type.
func receiver(name string) string {
	if name == "" {
		return "client"
	}
	return strings.ToLower(name[:1]) + name[1:] + "Client"
}

// emitClient writes the type and the constructor of one interface.
func emitClient(b *strings.Builder, in iface) {
	recv := receiver(in.Name)
	fmt.Fprintf(b, "// %s calls the %s service over HTTP.\n", recv, in.Name)
	fmt.Fprintf(b, "type %s struct {\n\trt *client.Client\n}\n\n", recv)

	b.WriteString("// The assignment proves that the generated type satisfies the interface.\n")
	fmt.Fprintf(b, "var _ %s = (*%s)(nil)\n\n", in.Name, recv)

	fmt.Fprintf(b, "// New%s returns a client of the %s service.\n", in.Name, in.Name)
	b.WriteString("//\n")
	fmt.Fprintf(b, "// The directive states the base address %s. An option after it replaces a\n", in.Base)
	b.WriteString("// default, so a test points the client at httptest.\n")
	fmt.Fprintf(b, "func New%s(opts ...client.Option) (%s, error) {\n", in.Name, in.Name)
	b.WriteString("\tsettings := []client.Option{\n")
	fmt.Fprintf(b, "\t\tclient.WithBaseURL(%s),\n", strconv.Quote(in.Base))
	fmt.Fprintf(b, "\t\tclient.WithAuth(client.Auth(%s)),\n", strconv.Quote(in.Auth))
	if in.Timeout != "" {
		fmt.Fprintf(b, "\t\tclient.WithTimeout(%s),\n", durationLiteral(in.Timeout))
	}
	if in.Attempts != "" {
		fmt.Fprintf(b, "\t\tclient.WithAttempts(%s),\n", in.Attempts)
	}
	if in.Backoff != "" {
		fmt.Fprintf(b, "\t\tclient.WithBackoff(%s),\n", durationLiteral(in.Backoff))
	}
	b.WriteString("\t}\n")
	fmt.Fprintf(b, "\trt, err := client.New(%s, append(settings, opts...)...)\n", strconv.Quote(in.Name))
	b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	fmt.Fprintf(b, "\treturn &%s{rt: rt}, nil\n}\n\n", recv)
}

// durationLiteral turns a duration of a directive into a call that parses it
// at build time. The generator proved the value, so the call cannot fail.
func durationLiteral(value string) string {
	return fmt.Sprintf("client.MustDuration(%s)", strconv.Quote(value))
}

// emitMethod writes one method of the generated type.
func emitMethod(b *strings.Builder, in iface, m method) {
	recv := receiver(in.Name)
	fmt.Fprintf(b, "// %s calls %s %s.\n", m.Name, m.HTTP, m.Path)
	fmt.Fprintf(b, "func (c *%s) %s(%s) %s {\n", recv, m.Name, signature(m), results(m))

	if m.Result != "" && !m.ResultPointer {
		fmt.Fprintf(b, "\tvar out %s\n", m.Result)
	}
	if m.Result != "" && m.ResultPointer {
		fmt.Fprintf(b, "\tout := new(%s)\n", m.Result)
	}

	b.WriteString("\treq := client.Request{\n")
	fmt.Fprintf(b, "\t\tOp:         %s,\n", strconv.Quote(m.Name))
	fmt.Fprintf(b, "\t\tMethod:     %s,\n", strconv.Quote(m.HTTP))
	fmt.Fprintf(b, "\t\tPath:       %s,\n", pathExpr(m))
	fmt.Fprintf(b, "\t\tIdempotent: %t,\n", m.Idempotent)
	if m.Body != "" {
		fmt.Fprintf(b, "\t\tBody:       %s,\n", m.Body)
	}
	b.WriteString("\t}\n")

	if len(m.Query) > 0 {
		b.WriteString("\treq.Query = client.NewQuery()\n")
		for _, f := range m.Query {
			emitSet(b, "req.Query", m.Option, f)
		}
	}
	if len(m.Header) > 0 {
		b.WriteString("\treq.Header = client.NewHeader()\n")
		for _, f := range m.Header {
			emitSet(b, "req.Header", m.Option, f)
		}
	}

	switch {
	case m.Result == "":
		b.WriteString("\treturn c.rt.Do(ctx, req, nil)\n")
	case m.ResultPointer:
		b.WriteString("\tif err := c.rt.Do(ctx, req, out); err != nil {\n\t\treturn nil, err\n\t}\n")
		b.WriteString("\treturn out, nil\n")
	default:
		b.WriteString("\tif err := c.rt.Do(ctx, req, &out); err != nil {\n\t\treturn out, err\n\t}\n")
		b.WriteString("\treturn out, nil\n")
	}
	b.WriteString("}\n\n")
}

// emitSet writes one query line or one header line.
func emitSet(b *strings.Builder, target, option string, f field) {
	value := option + "." + f.Go
	expr := value
	if f.Pointer {
		expr = "*" + value
	}
	set := fmt.Sprintf("\t%s.Set(%s, %s)\n", target, strconv.Quote(f.Wire), asString(expr, f.Kind))
	switch {
	case f.Pointer:
		fmt.Fprintf(b, "\tif %s != nil {\n\t%s\t}\n", value, set)
	case f.OmitEmpty:
		fmt.Fprintf(b, "\tif %s != %s {\n\t%s\t}\n", value, zero(f.Kind), set)
	default:
		b.WriteString(set)
	}
}

// zero returns the zero value of a kind.
func zero(k kind) string {
	switch k {
	case kindString:
		return `""`
	case kindBool:
		return "false"
	default:
		return "0"
	}
}

// asString turns a value into a string expression.
func asString(expr string, k kind) string {
	switch k {
	case kindInt:
		return "client.Int(int64(" + expr + "))"
	case kindUint:
		return "client.Uint(uint64(" + expr + "))"
	case kindFloat:
		return "client.Float(float64(" + expr + "))"
	case kindBool:
		return "client.Bool(" + expr + ")"
	default:
		return expr
	}
}

// signature returns the parameter list of a method.
func signature(m method) string {
	parts := []string{"ctx context.Context"}
	for _, a := range m.PathArgs {
		parts = append(parts, a.Name+" "+a.Type)
	}
	if m.Option != "" {
		parts = append(parts, m.Option+" "+m.OptionType)
	}
	if m.Body != "" {
		parts = append(parts, m.Body+" "+m.BodyType)
	}
	return strings.Join(parts, ", ")
}

// results returns the result list of a method.
func results(m method) string {
	switch {
	case m.Result == "":
		return "error"
	case m.ResultPointer:
		return "(*" + m.Result + ", error)"
	default:
		return "(" + m.Result + ", error)"
	}
}

// pathExpr returns the expression that builds the path of one call.
func pathExpr(m method) string {
	if len(m.PathArgs) == 0 {
		return strconv.Quote(m.Path)
	}
	var parts []string
	rest := m.Path
	i := 0
	for {
		open := strings.Index(rest, "{")
		if open < 0 || i >= len(m.PathArgs) {
			break
		}
		closing := strings.Index(rest[open:], "}")
		if closing < 0 {
			break
		}
		if open > 0 {
			parts = append(parts, strconv.Quote(rest[:open]))
		}
		a := m.PathArgs[i]
		if a.Kind == kindString {
			parts = append(parts, "client.Escape("+a.Name+")")
		} else {
			parts = append(parts, asString(a.Name, a.Kind))
		}
		rest = rest[open+closing+1:]
		i++
	}
	if rest != "" {
		parts = append(parts, strconv.Quote(rest))
	}
	return strings.Join(parts, " + ")
}
