package codegen_test

import (
	"errors"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/alternayte/avero/codegen"
)

// write puts one Go file into a new directory and returns the directory.
func write(t *testing.T, source string) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "posts.go"), []byte(source), 0o600); err != nil {
		t.Fatalf("WriteFile returned an error: %v", err)
	}
	return dir
}

// header is the preamble that every fixture shares.
const header = `package posts

import "github.com/alternayte/avero/router"

type Module struct{}

`

// generate runs the generator and returns the generated source.
func generate(t *testing.T, source string) string {
	t.Helper()
	dir := write(t, header+source)
	files, err := codegen.Generate(dir)
	if err != nil {
		t.Fatalf("Generate returned an error: %v", err)
	}
	if len(files) != 1 {
		t.Fatalf("Generate wrote %d files, want 1", len(files))
	}
	body, err := os.ReadFile(files[0])
	if err != nil {
		t.Fatalf("ReadFile returned an error: %v", err)
	}
	return string(body)
}

// faultOf runs the generator and returns the fault that it reports.
func faultOf(t *testing.T, source string) *codegen.Fault {
	t.Helper()
	dir := write(t, header+source)
	_, err := codegen.Generate(dir)
	if err == nil {
		t.Fatal("Generate accepted a source that holds a fault")
	}
	var f *codegen.Fault
	if !errors.As(err, &f) {
		t.Fatalf("err is %T, want *codegen.Fault: %v", err, err)
	}
	return f
}

const simple = `type CreateInput struct {
	Title string ` + "`json:\"title\" form:\"title\" validate:\"required\"`" + `
}

func (m *Module) Create(ctx *router.Ctx, in CreateInput) (router.Response, error) {
	return router.NoContent(), nil
}
`

func TestGenerateWritesTheBindAndValidateMethods(t *testing.T) {
	out := generate(t, simple)
	if !strings.Contains(out, "func (in *CreateInput) Bind(c *router.Ctx) error") {
		t.Fatalf("the file holds no Bind method:\n%s", out)
	}
	if !strings.Contains(out, "func (in *CreateInput) Validate(c *router.Ctx, f *router.Fields)") {
		t.Fatalf("the file holds no Validate method:\n%s", out)
	}
}

func TestTheGeneratedFileIsMarkedAsGenerated(t *testing.T) {
	out := generate(t, simple)
	first := strings.SplitN(out, "\n", 2)[0]
	// The line that every Go tool recognises. See go/build.
	if !strings.HasPrefix(first, "// Code generated by ") || !strings.HasSuffix(first, " DO NOT EDIT.") {
		t.Fatalf("the first line is %q", first)
	}
}

func TestTheGeneratedFileDoesNotImportReflect(t *testing.T) {
	out := generate(t, simple)
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "zz_generated.go", out, parser.ImportsOnly)
	if err != nil {
		t.Fatalf("the generated file does not parse: %v\n%s", err, out)
	}
	for _, imp := range file.Imports {
		if imp.Path.Value == `"reflect"` {
			t.Fatalf("the generated file imports reflect:\n%s", out)
		}
	}
}

func TestTheGeneratedFileParses(t *testing.T) {
	out := generate(t, simple)
	fset := token.NewFileSet()
	if _, err := parser.ParseFile(fset, "zz_generated.go", out, 0); err != nil {
		t.Fatalf("the generated file does not parse: %v\n%s", err, out)
	}
}

func TestAnInputThatNoHandlerTakesIsNotGenerated(t *testing.T) {
	out := generate(t, simple+`
type Unused struct {
	Name string `+"`json:\"name\"`"+`
}
`)
	if strings.Contains(out, "Unused") {
		t.Fatalf("the generator wrote binding for a type that no handler takes:\n%s", out)
	}
}

func TestAPackageWithNoHandlerWritesNoFile(t *testing.T) {
	dir := write(t, header+`type Thing struct{ Name string }`)
	files, err := codegen.Generate(dir)
	if err != nil {
		t.Fatalf("Generate returned an error: %v", err)
	}
	if len(files) != 0 {
		t.Fatalf("Generate wrote %v, want nothing", files)
	}
	if _, err := os.Stat(filepath.Join(dir, "zz_generated.go")); !os.IsNotExist(err) {
		t.Fatal("Generate wrote a file for a package with no handler")
	}
}

func TestTwoHandlersOnOneInputWriteOneBinding(t *testing.T) {
	out := generate(t, simple+`
func (m *Module) Update(ctx *router.Ctx, in CreateInput) (router.Response, error) {
	return router.NoContent(), nil
}
`)
	if n := strings.Count(out, "func (in *CreateInput) Bind("); n != 1 {
		t.Fatalf("the generator wrote %d Bind methods, want 1", n)
	}
}

func TestGenerateIsStableAcrossRuns(t *testing.T) {
	first := generate(t, simple)
	for range 3 {
		if next := generate(t, simple); next != first {
			t.Fatalf("the output changed between runs:\n%s\n---\n%s", first, next)
		}
	}
}

func TestCheckPassesForACurrentFile(t *testing.T) {
	dir := write(t, header+simple)
	if _, err := codegen.Generate(dir); err != nil {
		t.Fatalf("Generate returned an error: %v", err)
	}
	if err := codegen.Check(dir); err != nil {
		t.Fatalf("Check reported a fault for a current file: %v", err)
	}
}

func TestCheckFailsForAStaleFile(t *testing.T) {
	dir := write(t, header+simple)
	if _, err := codegen.Generate(dir); err != nil {
		t.Fatalf("Generate returned an error: %v", err)
	}
	path := filepath.Join(dir, "zz_generated.go")
	body, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile returned an error: %v", err)
	}
	if err := os.WriteFile(path, append(body, []byte("\n// a hand edit\n")...), 0o600); err != nil {
		t.Fatalf("WriteFile returned an error: %v", err)
	}

	err = codegen.Check(dir)
	if err == nil {
		t.Fatal("Check accepted a stale file")
	}
	if !strings.Contains(err.Error(), "zz_generated.go") {
		t.Fatalf("the fault does not name the file: %v", err)
	}
	if !strings.Contains(err.Error(), "avero generate") {
		t.Fatalf("the repair does not name the command: %v", err)
	}
}

func TestCheckFailsForAMissingFile(t *testing.T) {
	dir := write(t, header+simple)
	if err := codegen.Check(dir); err == nil {
		t.Fatal("Check accepted a package with no generated file")
	}
}

// generateFaults runs the generator and returns the whole fault list.
func generateFaults(dir string) ([]string, error) { return codegen.Generate(dir) }

func TestAnInputWithNoFieldCompiles(t *testing.T) {
	// A form with no field is a real shape: a page that only proves the CSRF
	// token. The generated Bind must read no request, because a declared and
	// unused variable does not compile.
	dir := t.TempDir()
	source := `package api

import "github.com/alternayte/avero/router"

type Module struct{}

type EmptyInput struct{}

func (m *Module) Show(c *router.Ctx, in EmptyInput) (router.Response, error) {
	return router.NoContent(), nil
}
`
	if err := os.WriteFile(filepath.Join(dir, "api.go"), []byte(source), 0o644); err != nil {
		t.Fatalf("WriteFile returned %v", err)
	}
	if _, err := codegen.Generate(dir); err != nil {
		t.Fatalf("Generate returned %v, want nil", err)
	}
	body, err := os.ReadFile(filepath.Join(dir, codegen.GeneratedFile))
	if err != nil {
		t.Fatalf("ReadFile returned %v", err)
	}
	if strings.Contains(string(body), "r := c.Request()") {
		t.Fatalf("the generated Bind reads the request of an input with no field:\n%s", body)
	}
}
