package codegen

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// generatedHeader is the line that every Go tool recognises. See go/build.
const generatedHeader = "// Code generated by avero generate. DO NOT EDIT."

// routerImport is the package that generated code calls.
const routerImport = "github.com/alternayte/avero/router"

// emit writes the source of one zz_generated.go file.
func emit(p pkg) ([]byte, error) {
	var body strings.Builder
	imports := map[string]bool{routerImport: true}

	for _, in := range p.Inputs {
		emitBind(&body, in, imports)
		emitValidate(&body, in, imports)
	}

	var head strings.Builder
	head.WriteString(generatedHeader + "\n//\n")
	head.WriteString("// The source of this file is the handler set of this package. Change the\n")
	head.WriteString("// input types and run `avero generate`. Do not edit this file by hand.\n\n")
	fmt.Fprintf(&head, "package %s\n\n", p.Name)

	names := make([]string, 0, len(imports))
	for name := range imports {
		names = append(names, name)
	}
	sort.Strings(names)
	head.WriteString("import (\n")
	for _, name := range names {
		if !strings.Contains(name, ".") {
			fmt.Fprintf(&head, "\t%s\n", strconv.Quote(name))
		}
	}
	head.WriteString("\n")
	for _, name := range names {
		if strings.Contains(name, ".") {
			fmt.Fprintf(&head, "\t%s\n", strconv.Quote(name))
		}
	}
	head.WriteString(")\n\n")

	return format.Source([]byte(head.String() + body.String()))
}

// emitBind writes the Bind method of one input type.
func emitBind(b *strings.Builder, in input, imports map[string]bool) {
	fmt.Fprintf(b, "// Bind fills %s from the request.\n", in.Name)
	b.WriteString("//\n")
	b.WriteString("// The sources are the JSON body, the form, the query and the path, in that\n")
	b.WriteString("// order. A later source replaces an earlier one, so the path wins.\n")
	fmt.Fprintf(b, "func (in *%s) Bind(c *router.Ctx) error {\n", in.Name)
	b.WriteString("\tr := c.Request()\n")

	if anyJSON(in) {
		imports["encoding/json"] = true
		b.WriteString("\n\tif router.HasJSONBody(r) {\n")
		b.WriteString("\t\tif err := json.NewDecoder(r.Body).Decode(in); err != nil {\n")
		b.WriteString("\t\t\treturn err\n\t\t}\n\t}\n")
	}
	if anyForm(in) {
		b.WriteString("\n\tif err := r.ParseForm(); err != nil {\n\t\treturn err\n\t}\n")
	}
	if anyQuery(in) {
		// url.URL.Query parses the whole string, so read it one time.
		b.WriteString("\n\tq := r.URL.Query()\n")
	}

	for _, source := range []struct {
		label string
		name  func(field) string
		read  string
		list  string
		from  string
	}{
		{"form", func(f field) string { return f.Form }, "router.Value", "router.Values", "r.PostForm"},
		{"query", func(f field) string { return f.Query }, "router.Value", "router.Values", "q"},
		{"path", func(f field) string { return f.Path }, "router.PathValue", "", "r"},
	} {
		for _, f := range in.Fields {
			member := source.name(f)
			if member == "" {
				continue
			}
			fmt.Fprintf(b, "\n\t// %s: %s\n", source.label, member)
			if f.Kind == kindStringSlice {
				if source.list == "" {
					// A path wildcard holds one value.
					emitScalar(b, f, member, source.read, source.from, imports)
					continue
				}
				fmt.Fprintf(b, "\tif v, ok := %s(%s, %s); ok {\n\t\tin.%s = v\n\t}\n",
					source.list, source.from, strconv.Quote(member), f.Name)
				continue
			}
			emitScalar(b, f, member, source.read, source.from, imports)
		}
	}

	b.WriteString("\n\treturn nil\n}\n\n")
}

// emitScalar writes the read and the conversion of one scalar field.
func emitScalar(b *strings.Builder, f field, member, read, from string, imports map[string]bool) {
	quoted := strconv.Quote(member)
	fmt.Fprintf(b, "\tif v, ok := %s(%s, %s); ok {\n", read, from, quoted)
	switch f.Kind {
	case kindString:
		fmt.Fprintf(b, "\t\tin.%s = v\n", f.Name)
	case kindStringSlice:
		fmt.Fprintf(b, "\t\tin.%s = []string{v}\n", f.Name)
	case kindBool:
		imports["strconv"] = true
		b.WriteString("\t\tparsed, err := strconv.ParseBool(v)\n")
		fmt.Fprintf(b, "\t\tif err != nil {\n\t\t\treturn router.NewBindFault(%s, %s)\n\t\t}\n",
			quoted, strconv.Quote(f.Kind.want()))
		fmt.Fprintf(b, "\t\tin.%s = parsed\n", f.Name)
	case kindInt:
		imports["strconv"] = true
		fmt.Fprintf(b, "\t\tparsed, err := strconv.ParseInt(v, 10, %d)\n", bits(f.Type))
		fmt.Fprintf(b, "\t\tif err != nil {\n\t\t\treturn router.NewBindFault(%s, %s)\n\t\t}\n",
			quoted, strconv.Quote(f.Kind.want()))
		fmt.Fprintf(b, "\t\tin.%s = %s(parsed)\n", f.Name, f.Type)
	case kindUint:
		imports["strconv"] = true
		fmt.Fprintf(b, "\t\tparsed, err := strconv.ParseUint(v, 10, %d)\n", bits(f.Type))
		fmt.Fprintf(b, "\t\tif err != nil {\n\t\t\treturn router.NewBindFault(%s, %s)\n\t\t}\n",
			quoted, strconv.Quote(f.Kind.want()))
		fmt.Fprintf(b, "\t\tin.%s = %s(parsed)\n", f.Name, f.Type)
	case kindFloat:
		imports["strconv"] = true
		fmt.Fprintf(b, "\t\tparsed, err := strconv.ParseFloat(v, %d)\n", bits(f.Type))
		fmt.Fprintf(b, "\t\tif err != nil {\n\t\t\treturn router.NewBindFault(%s, %s)\n\t\t}\n",
			quoted, strconv.Quote(f.Kind.want()))
		fmt.Fprintf(b, "\t\tin.%s = %s(parsed)\n", f.Name, f.Type)
	case kindDuration:
		imports["time"] = true
		b.WriteString("\t\tparsed, err := time.ParseDuration(v)\n")
		fmt.Fprintf(b, "\t\tif err != nil {\n\t\t\treturn router.NewBindFault(%s, %s)\n\t\t}\n",
			quoted, strconv.Quote(f.Kind.want()))
		fmt.Fprintf(b, "\t\tin.%s = parsed\n", f.Name)
	case kindTime:
		imports["time"] = true
		b.WriteString("\t\tparsed, err := time.Parse(time.RFC3339, v)\n")
		fmt.Fprintf(b, "\t\tif err != nil {\n\t\t\treturn router.NewBindFault(%s, %s)\n\t\t}\n",
			quoted, strconv.Quote(f.Kind.want()))
		fmt.Fprintf(b, "\t\tin.%s = parsed\n", f.Name)
	}
	b.WriteString("\t}\n")
}

// emitValidate writes the Validate method of one input type.
func emitValidate(b *strings.Builder, in input, imports map[string]bool) {
	fmt.Fprintf(b, "// Validate checks %s and records one message for each field that failed.\n", in.Name)
	fmt.Fprintf(b, "func (in *%s) Validate(c *router.Ctx, f *router.Fields) {\n", in.Name)
	for _, fl := range in.Fields {
		for _, r := range fl.Rules {
			emitRule(b, fl, r, imports)
		}
	}
	if in.HasCheck {
		b.WriteString("\n\t// The custom rule of this input type.\n")
		b.WriteString("\tin.Check(c, f)\n")
	}
	b.WriteString("}\n\n")
}

// emitRule writes one rule.
func emitRule(b *strings.Builder, f field, r rule, imports map[string]bool) {
	name := strconv.Quote(f.Name)
	switch r.Name {
	case ruleRequired:
		switch f.Kind {
		case kindString:
			imports["strings"] = true
			fmt.Fprintf(b, "\tif strings.TrimSpace(in.%s) == \"\" {\n", f.Name)
		case kindStringSlice:
			fmt.Fprintf(b, "\tif len(in.%s) == 0 {\n", f.Name)
		case kindTime:
			fmt.Fprintf(b, "\tif in.%s.IsZero() {\n", f.Name)
		default:
			fmt.Fprintf(b, "\tif in.%s == 0 {\n", f.Name)
		}
		fmt.Fprintf(b, "\t\tf.Add(%s, \"is required\")\n\t}\n", name)
	case ruleMin:
		if f.Kind == kindString {
			imports["unicode/utf8"] = true
			fmt.Fprintf(b, "\tif utf8.RuneCountInString(in.%s) < %s {\n", f.Name, r.Arg)
			fmt.Fprintf(b, "\t\tf.Add(%s, \"must hold at least %s characters\")\n\t}\n", name, r.Arg)
			return
		}
		fmt.Fprintf(b, "\tif in.%s < %s {\n", f.Name, r.Arg)
		fmt.Fprintf(b, "\t\tf.Add(%s, \"must be %s or more\")\n\t}\n", name, r.Arg)
	case ruleMax:
		if f.Kind == kindString {
			imports["unicode/utf8"] = true
			fmt.Fprintf(b, "\tif utf8.RuneCountInString(in.%s) > %s {\n", f.Name, r.Arg)
			fmt.Fprintf(b, "\t\tf.Add(%s, \"must hold at most %s characters\")\n\t}\n", name, r.Arg)
			return
		}
		fmt.Fprintf(b, "\tif in.%s > %s {\n", f.Name, r.Arg)
		fmt.Fprintf(b, "\t\tf.Add(%s, \"must be %s or less\")\n\t}\n", name, r.Arg)
	case ruleEmail:
		fmt.Fprintf(b, "\tif in.%s != \"\" && !router.IsEmail(in.%s) {\n", f.Name, f.Name)
		fmt.Fprintf(b, "\t\tf.Add(%s, \"must be an email address\")\n\t}\n", name)
	case ruleUUID:
		fmt.Fprintf(b, "\tif in.%s != \"\" && !router.IsUUID(in.%s) {\n", f.Name, f.Name)
		fmt.Fprintf(b, "\t\tf.Add(%s, \"must be a UUID\")\n\t}\n", name)
	case ruleOneOf:
		quoted := make([]string, 0, len(r.Values))
		for _, v := range r.Values {
			quoted = append(quoted, strconv.Quote(v))
		}
		fmt.Fprintf(b, "\tif in.%s != \"\" && !router.OneOf(in.%s, %s) {\n",
			f.Name, f.Name, strings.Join(quoted, ", "))
		fmt.Fprintf(b, "\t\tf.Add(%s, \"must be one of %s\")\n\t}\n",
			name, strings.Join(r.Values, ", "))
	}
}

// anyJSON reports whether one field binds from the body.
func anyJSON(in input) bool {
	for _, f := range in.Fields {
		if f.JSON != "" {
			return true
		}
	}
	return false
}

// anyQuery reports whether one field binds from the query.
func anyQuery(in input) bool {
	for _, f := range in.Fields {
		if f.Query != "" {
			return true
		}
	}
	return false
}

// anyForm reports whether one field binds from the form.
func anyForm(in input) bool {
	for _, f := range in.Fields {
		if f.Form != "" {
			return true
		}
	}
	return false
}

// bits returns the width of a sized numeric type.
func bits(typeText string) int {
	switch typeText {
	case "int8", "uint8":
		return 8
	case "int16", "uint16":
		return 16
	case "int32", "uint32", "float32":
		return 32
	default:
		return 64
	}
}
