// Code generated by drel. DO NOT EDIT.

package model

import (
	"context"

	"github.com/alternayte/drel"
	uuid "github.com/google/uuid"
)

var Posts = struct {
	ID        drel.ComparableColumn[uuid.UUID]
	Title     drel.StringColumn
	Body      drel.StringColumn
	CreatedAt drel.TimeColumn
	UpdatedAt drel.TimeColumn
}{
	ID:        drel.NewComparableCol[uuid.UUID]("id"),
	Title:     drel.NewStringCol("title"),
	Body:      drel.NewStringCol("body"),
	CreatedAt: drel.NewTimeCol("created_at"),
	UpdatedAt: drel.NewTimeCol("updated_at"),
}

func scanPost(row drel.Row) (*Post, error) {
	p := &Post{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	err := row.Scan(idPtr, &p.Title, &p.Body, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	return p, nil
}

type postSnapshot struct {
	Title string
	Body  string
}

func snapshotPost(p *Post) any {
	return postSnapshot{Title: p.Title, Body: p.Body}
}

func diffPost(p *Post, snap any) []drel.FieldChange {
	s := snap.(postSnapshot)
	var changes []drel.FieldChange
	if p.Title != s.Title {
		changes = append(changes, drel.FieldChange{Column: "title", Value: p.Title})
	}
	if p.Body != s.Body {
		changes = append(changes, drel.FieldChange{Column: "body", Value: p.Body})
	}
	return changes
}

func postPKValue(p *Post) any {
	return p.ID()
}

func postColumnValue(p *Post, idx int) any {
	switch idx {
	case 0:
		return p.ID()
	case 1:
		return p.Title
	case 2:
		return p.Body
	case 3:
		return p.CreatedAt()
	case 4:
		return p.UpdatedAt()
	}
	return nil
}

func postInsertColumns(p *Post) ([]string, []any) {
	return []string{"title", "body"}, []any{p.Title, p.Body}
}

func postScanReturning(p *Post, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

func postNormalizeKey(v any) any {
	return drel.NormalizeUUIDKey(v)
}

func postKeyIsZero(p *Post) bool {
	var zero uuid.UUID
	return p.ID() == zero
}

func postScanGenerated(p *Post, row drel.Row) error {
	_, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(createdAtPtr, updatedAtPtr)
}

var PostMeta = drel.ModelMeta[Post]{
	Table:         "posts",
	Columns:       []string{"id", "title", "body", "created_at", "updated_at"},
	PKColumn:      "id",
	Scan:          scanPost,
	Snapshot:      snapshotPost,
	Diff:          diffPost,
	PKValue:       postPKValue,
	InsertColumns: postInsertColumns,
	ScanReturning: postScanReturning,
	ColumnValue:   postColumnValue,
	NormalizeKey:  postNormalizeKey,
	KeyStrategy:   drel.KeyAppAssigned,
	GenerateKey:   drel.UUIDv7Key,
	SetKey:        func(p *Post, key any) { p.SetID(key.(uuid.UUID)) },
	KeyIsZero:     postKeyIsZero,
	ScanGenerated: postScanGenerated,
}

type PostRepository struct {
	*drel.Repository[Post]
}

func (r *PostRepository) FindByID(ctx context.Context, id uuid.UUID) (*Post, error) {
	return r.Find(ctx, id)
}

type TxPostRepository struct {
	*drel.TxRepository[Post]
}

func (r *TxPostRepository) FindByID(ctx context.Context, id uuid.UUID) (*Post, error) {
	return r.Find(ctx, id)
}
