CREATE TABLE "tasks" (
    "id" TEXT PRIMARY KEY,
    "title" TEXT NOT NULL,
    "done" INTEGER NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
