// Code generated by avero generate. DO NOT EDIT.
//
// The source of this file is the handler set of this package. Change the
// input types and run `avero generate`. Do not edit this file by hand.

package example

import (
	"encoding/json"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/alternayte/avero/router"
)

// Bind fills CreateInput from the request.
//
// The sources are the JSON body, the form, the query and the path, in that
// order. A later source replaces an earlier one, so the path wins.
func (in *CreateInput) Bind(c *router.Ctx) error {
	r := c.Request()

	if router.HasJSONBody(r) {
		if err := json.NewDecoder(r.Body).Decode(in); err != nil {
			return err
		}
	}

	if err := r.ParseForm(); err != nil {
		return err
	}

	q := r.URL.Query()

	// form: title
	if v, ok := router.Value(r.PostForm, "title"); ok {
		in.Title = v
	}

	// form: email
	if v, ok := router.Value(r.PostForm, "email"); ok {
		in.Email = v
	}

	// form: role
	if v, ok := router.Value(r.PostForm, "role"); ok {
		in.Role = v
	}

	// form: notify
	if v, ok := router.Value(r.PostForm, "notify"); ok {
		parsed, err := strconv.ParseBool(v)
		if err != nil {
			return router.NewBindFault("notify", "true or false")
		}
		in.Notify = parsed
	}

	// query: page
	if v, ok := router.Value(q, "page"); ok {
		parsed, err := strconv.ParseInt(v, 10, 64)
		if err != nil {
			return router.NewBindFault("page", "a whole number")
		}
		in.Page = int(parsed)
	}

	// query: size
	if v, ok := router.Value(q, "size"); ok {
		parsed, err := strconv.ParseInt(v, 10, 64)
		if err != nil {
			return router.NewBindFault("size", "a whole number")
		}
		in.Size = int64(parsed)
	}

	// query: ratio
	if v, ok := router.Value(q, "ratio"); ok {
		parsed, err := strconv.ParseFloat(v, 64)
		if err != nil {
			return router.NewBindFault("ratio", "a number")
		}
		in.Ratio = float64(parsed)
	}

	// query: notify
	if v, ok := router.Value(q, "notify"); ok {
		parsed, err := strconv.ParseBool(v)
		if err != nil {
			return router.NewBindFault("notify", "true or false")
		}
		in.Notify = parsed
	}

	// query: timeout
	if v, ok := router.Value(q, "timeout"); ok {
		parsed, err := time.ParseDuration(v)
		if err != nil {
			return router.NewBindFault("timeout", "a duration such as 15s")
		}
		in.Timeout = parsed
	}

	// query: starts_at
	if v, ok := router.Value(q, "starts_at"); ok {
		parsed, err := time.Parse(time.RFC3339, v)
		if err != nil {
			return router.NewBindFault("starts_at", "a time in RFC 3339 form")
		}
		in.StartsAt = parsed
	}

	// query: tags
	if v, ok := router.Values(q, "tags"); ok {
		in.Tags = v
	}

	// path: board_id
	if v, ok := router.PathValue(r, "board_id"); ok {
		in.BoardID = v
	}

	return nil
}

// Validate checks CreateInput and records one message for each field that failed.
func (in *CreateInput) Validate(c *router.Ctx, f *router.Fields) {
	if strings.TrimSpace(in.BoardID) == "" {
		f.Add("board_id", "is required")
	}
	if in.BoardID != "" && !router.IsUUID(in.BoardID) {
		f.Add("board_id", "must be a UUID")
	}
	if strings.TrimSpace(in.Title) == "" {
		f.Add("title", "is required")
	}
	if utf8.RuneCountInString(in.Title) < 3 {
		f.Add("title", "must hold at least 3 characters")
	}
	if utf8.RuneCountInString(in.Title) > 50 {
		f.Add("title", "must hold at most 50 characters")
	}
	if strings.TrimSpace(in.Email) == "" {
		f.Add("email", "is required")
	}
	if in.Email != "" && !router.IsEmail(in.Email) {
		f.Add("email", "must be an email address")
	}
	if in.Role != "" && !router.OneOf(in.Role, "admin", "member", "viewer") {
		f.Add("role", "must be one of admin, member, viewer")
	}
	if in.Page < 1 {
		f.Add("page", "must be 1 or more")
	}
	if in.Page > 100 {
		f.Add("page", "must be 100 or less")
	}

	// The custom rule of this input type.
	in.Check(c, f)
}

// Bind fills ListInput from the request.
//
// The sources are the JSON body, the form, the query and the path, in that
// order. A later source replaces an earlier one, so the path wins.
func (in *ListInput) Bind(c *router.Ctx) error {
	r := c.Request()

	q := r.URL.Query()

	// query: q
	if v, ok := router.Value(q, "q"); ok {
		in.Query = v
	}

	return nil
}

// Validate checks ListInput and records one message for each field that failed.
func (in *ListInput) Validate(c *router.Ctx, f *router.Fields) {
	if utf8.RuneCountInString(in.Query) > 64 {
		f.Add("q", "must hold at most 64 characters")
	}
}
