// Code generated by drel. DO NOT EDIT.

package db

import (
	"context"

	model "board/internal/features/tasks/model"
	"github.com/alternayte/drel"
)

type DB struct {
	*drel.Engine
	Tasks   *model.TaskRepository
	Modules Modules
}

func Open(dsn string, opts ...drel.Option) (*DB, error) {
	engine, err := drel.NewEngine(dsn, opts...)
	if err != nil {
		return nil, err
	}
	return &DB{
		Engine: engine,
		Tasks:  &model.TaskRepository{Repository: drel.NewRepository(engine, model.TaskMeta)},
		Modules: Modules{
			Tasks: TasksRepos{
				Tasks: &model.TaskRepository{Repository: drel.NewRepository(engine, model.TaskMeta)},
			},
		},
	}, nil
}

// TxRepos holds the tracked repositories of one transaction. Load through
// the fields, stage with Add and Remove, then let WithTx commit.
type TxRepos struct {
	Tasks   *model.TxTaskRepository
	Modules TxModules
}

// Tx returns the tracked repositories bound to the transaction in ctx.
// It panics if no transaction is present, so wrap the call in WithTx.
func (db *DB) Tx(ctx context.Context) TxRepos {
	tx := drel.MustFromContext(ctx)
	return TxRepos{
		Tasks: &model.TxTaskRepository{TxRepository: drel.NewTxRepository(tx, model.TaskMeta)},
	}
}

// TasksRepos holds the untracked repositories of the "tasks" module.
type TasksRepos struct {
	Tasks *model.TaskRepository
}

// TasksTxRepos holds the tracked repositories of the "tasks" module.
type TasksTxRepos struct {
	Tasks *model.TxTaskRepository
}

// Modules groups the untracked repositories by feature slice, so a slice
// reaches only its own models.
type Modules struct {
	Tasks TasksRepos
}

// TxModules groups the tracked repositories by feature slice. Every set is
// bound to the same transaction.
type TxModules struct {
	Tasks TasksTxRepos
}

// WithTx runs fn inside a transaction and puts that transaction in the
// context it passes to fn. Reach the tracked repositories with db.Tx(ctx).
// A nested call opens a savepoint on the same transaction.
func (db *DB) WithTx(ctx context.Context, fn func(ctx context.Context) error, opts ...drel.TxOption) error {
	return db.Engine.WithTx(ctx, fn, opts...)
}
