// Code generated by avero generate. DO NOT EDIT.
//
// The source of this file is the handler set of this package. Change the
// input types and run `avero generate`. Do not edit this file by hand.

package posts

import (
	"encoding/json"
	"strings"
	"unicode/utf8"

	"github.com/alternayte/avero/module"
	"github.com/alternayte/avero/router"
)

// Bind fills CreateInput from the request.
//
// The sources are the JSON body, the form, the query and the path, in that
// order. A later source replaces an earlier one, so the path wins.
func (in *CreateInput) Bind(c *router.Ctx) error {
	r := c.Request()

	if router.HasJSONBody(r) {
		if err := json.NewDecoder(r.Body).Decode(in); err != nil {
			return err
		}
	}

	return nil
}

// Validate checks CreateInput and records one message for each field that failed.
func (in *CreateInput) Validate(c *router.Ctx, f *router.Fields) {
	if strings.TrimSpace(in.Title) == "" {
		f.Add("title", "is required")
	}
	if utf8.RuneCountInString(in.Title) < 3 {
		f.Add("title", "must hold at least 3 characters")
	}
	if utf8.RuneCountInString(in.Title) > 80 {
		f.Add("title", "must hold at most 80 characters")
	}
	if strings.TrimSpace(in.Body) == "" {
		f.Add("body", "is required")
	}
	if utf8.RuneCountInString(in.Body) < 1 {
		f.Add("body", "must hold at least 1 characters")
	}
}

// Bind fills DeleteInput from the request.
//
// The sources are the JSON body, the form, the query and the path, in that
// order. A later source replaces an earlier one, so the path wins.
func (in *DeleteInput) Bind(c *router.Ctx) error {
	r := c.Request()

	// path: id
	if v, ok := router.PathValue(r, "id"); ok {
		in.ID = v
	}

	return nil
}

// Validate checks DeleteInput and records one message for each field that failed.
func (in *DeleteInput) Validate(c *router.Ctx, f *router.Fields) {
	if strings.TrimSpace(in.ID) == "" {
		f.Add("id", "is required")
	}
}

// Bind fills ListInput from the request.
//
// The sources are the JSON body, the form, the query and the path, in that
// order. A later source replaces an earlier one, so the path wins.
func (in *ListInput) Bind(c *router.Ctx) error {
	r := c.Request()

	q := r.URL.Query()

	// query: q
	if v, ok := router.Value(q, "q"); ok {
		in.Search = v
	}

	return nil
}

// Validate checks ListInput and records one message for each field that failed.
func (in *ListInput) Validate(c *router.Ctx, f *router.Fields) {
}

// Bind fills ShowInput from the request.
//
// The sources are the JSON body, the form, the query and the path, in that
// order. A later source replaces an earlier one, so the path wins.
func (in *ShowInput) Bind(c *router.Ctx) error {
	r := c.Request()

	// path: id
	if v, ok := router.PathValue(r, "id"); ok {
		in.ID = v
	}

	return nil
}

// Validate checks ShowInput and records one message for each field that failed.
func (in *ShowInput) Validate(c *router.Ctx, f *router.Fields) {
	if strings.TrimSpace(in.ID) == "" {
		f.Add("id", "is required")
	}
}

// Summaries returns the summary of each handler of Module.
//
// The comment of a handler states it. Change the comment and run
// `avero generate`.
func (m *Module) Summaries() map[string]string {
	return map[string]string{
		"Create": "Writes one post",
		"Delete": "Removes one post",
		"List":   "Answers every post",
		"Show":   "Answers one post",
	}
}

// Models returns the persistent models of Module.
//
// The model package of this feature states them. Change a field and run
// `avero generate`.
func (m *Module) Models() []module.ModelDesc {
	return []module.ModelDesc{
		{
			Name:  "Post",
			Table: "posts",
			Fields: []module.FieldDesc{
				{Name: "ID", Type: "uuid.UUID"},
				{Name: "Title", Type: "string"},
				{Name: "Body", Type: "string"},
				{Name: "CreatedAt", Type: "time.Time"},
				{Name: "UpdatedAt", Type: "time.Time"},
			},
		},
	}
}
